big updates

diff --git a/miscxrdb/.config/miscxrdb/bin/lfrun b/miscxrdb/.config/miscxrdb/bin/lfrun
--- a/miscxrdb/.config/miscxrdb/bin/lfrun
+++ b/miscxrdb/.config/miscxrdb/bin/lfrun
@@ -6,14 +6,16 @@ cleanup() {
   rm "$FIFO_UEBERZUG"
 }
 
-if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
-  lf "$@"
-else
-  [ ! -d "$HOME/.cache/lf" ] && mkdir --parents "$HOME/.cache/lf"
-  export FIFO_UEBERZUG="$HOME/.cache/lf/ueberzug-$$"
-  mkfifo "$FIFO_UEBERZUG"
-  ueberzug layer -s -p json <"$FIFO_UEBERZUG" &
-  exec 3>"$FIFO_UEBERZUG"
-  trap cleanup EXIT
-  lf "$@" 3>&-
-fi
+lf "$@"
+
+# if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
+#   lf "$@"
+# else
+#   [ ! -d "$HOME/.cache/lf" ] && mkdir --parents "$HOME/.cache/lf"
+#   export FIFO_UEBERZUG="$HOME/.cache/lf/ueberzug-$$"
+#   mkfifo "$FIFO_UEBERZUG"
+#   ueberzug layer -s -p json <"$FIFO_UEBERZUG" &
+#   exec 3>"$FIFO_UEBERZUG"
+#   trap cleanup EXIT
+#   lf "$@" 3>&-
+# fi
