chore(preview-tui): refactoring and delete stuff

diff --git a/nnn/.config/nnn/plugins/fzcd b/nnn/.config/nnn/plugins/fzcd
--- a/nnn/.config/nnn/plugins/fzcd
+++ b/nnn/.config/nnn/plugins/fzcd
@@ -52,60 +52,63 @@ elif ! [ -s "$LIST" ]; then
 fi
 
 if [ -n "$LIST" ]; then
-	if not_in_tmux; then
 
-		if type find >/dev/null 2>&1; then
-			tmpfile=$(mktemp /tmp/abc-script.XXXXXX)
+	if type find >/dev/null 2>&1; then
+		tmpfile=$(mktemp /tmp/abc-script.XXXXXX)
 
-			while IFS= read -r path; do
-				if [ -d "$path" ]; then
-					printf "%s\n" "$path" >>"$tmpfile"
-				elif [ -f "$path" ]; then
-					printf "%s\n" "$(dirname "$path")" >>"$tmpfile"
-				fi
-			done <"$LIST"
+		while IFS= read -r path; do
+			if [ -d "$path" ]; then
+				printf "%s\n" "$path" >>"$tmpfile"
+			elif [ -f "$path" ]; then
+				printf "%s\n" "$(dirname "$path")" >>"$tmpfile"
+			fi
+		done <"$LIST"
 
-			# sel=$(xargs -d '\n' -I{} find {} -type f -printf "%H//%P\n" <"$tmpfile" | sed '/.*\/\/\(\..*\|.*\/\..*\)/d; s:/\+:/:g' | fzf --delimiter / --tiebreak=begin --info=hidden)
-			# Alternative for 'fd'
-			# dunstify "$tmpfile"
+		# sel=$(xargs -d '\n' -I{} find {} -type f -printf "%H//%P\n" <"$tmpfile" | sed '/.*\/\/\(\..*\|.*\/\..*\)/d; s:/\+:/:g' | fzf --delimiter / --tiebreak=begin --info=hidden)
+		# Alternative for 'fd'
+		# dunstify "$tmpfile"
+		if not_in_tmux; then
 
 			pane_id_right=$(wezterm cli get-pane-direction right)
 			wezterm cli split-pane --bottom --move-pane-id "$pane_id_right" >/dev/null
 			wezterm cli activate-pane-direction Up
 
 			# sel=$(xargs -d '\n' fd -H -I . <"$tmpfile" | fzf --delimiter / --with-nth=-2,-1 --tiebreak=begin --info=hidden --prompt "Cd to> ")
-			sel=$(xargs -d '\n' fd -H -I . <"$tmpfile" | fzf --no-height --prompt "FzCD: ")
+			sel=$(xargs -d '\n' fd -H . <"$tmpfile" | fzf --no-height --prompt "FzCD: ")
 
 			wezterm cli split-pane --right --move-pane-id "$pane_id_right" --percent 85 >/dev/null
 			wezterm cli activate-pane-direction Left
 
-			rm "$tmpfile"
-
 		else
-			printf "find missing"
-			read -r _
-			exit 1
-		fi
-	fi
-
-	if [ -n "$sel" ]; then
-		if [ "$sel" = "." ] || { ! [ -d "$sel" ] && ! [ -f "$sel" ]; }; then
-			exit 0
+			sel=$(xargs -d '\n' fd -H . <"$tmpfile" | fzf-tmux -xC -w '60%' -h '50%' --prompt "FzCD: ")
 		fi
 
-		# Check if the selected path returned by fzf command is absolute
-		case $sel in
-		/*) nnn_cd "$sel" "$CTX" ;;
-		*)
-			# Remove "./" prefix if it exists
-			sel="${sel#./}"
+		rm "$tmpfile"
 
-			if [ "$PWD" = "/" ]; then
-				nnn_cd "/$sel" "$CTX"
-			else
-				nnn_cd "$PWD/$sel" "$CTX"
-			fi
-			;;
-		esac
+	else
+		printf "find missing"
+		read -r _
+		exit 1
 	fi
+fi
+
+if [ -n "$sel" ]; then
+	if [ "$sel" = "." ] || { ! [ -d "$sel" ] && ! [ -f "$sel" ]; }; then
+		exit 0
+	fi
+
+	# Check if the selected path returned by fzf command is absolute
+	case $sel in
+	/*) nnn_cd "$sel" "$CTX" ;;
+	*)
+		# Remove "./" prefix if it exists
+		sel="${sel#./}"
+
+		if [ "$PWD" = "/" ]; then
+			nnn_cd "/$sel" "$CTX"
+		else
+			nnn_cd "$PWD/$sel" "$CTX"
+		fi
+		;;
+	esac
 fi
