feat(preview-tui): refactor gif previewer

diff --git a/nnn/.config/nnn/plugins/fzcd b/nnn/.config/nnn/plugins/fzcd
--- a/nnn/.config/nnn/plugins/fzcd
+++ b/nnn/.config/nnn/plugins/fzcd
@@ -34,7 +34,14 @@ if ! type fzf >/dev/null 2>&1; then
 	exit 1
 fi
 
-if [ -n "$1" ] && [ "$(file -b --mime-type "$1")" = 'text/plain' ] && [ -e "$(head -1 "$1")" ]; then
+. "$HOME/.config/miscxrdb/fzf/fzf.config"
+
+not_in_tmux() {
+	[ -z "$TMUX" ]
+}
+
+# if [ -n "$1" ] && [ "$(file -b --mime-type "$1")" = 'text/plain' ] && [ -e "$(head -1 "$1")" ]; then
+if [ -n "$1" ]; then
 	LIST="$1"
 elif ! [ -s "$LIST" ]; then
 	sel=$(fzf)
@@ -45,46 +52,60 @@ elif ! [ -s "$LIST" ]; then
 fi
 
 if [ -n "$LIST" ]; then
-	if type find >/dev/null 2>&1; then
-		tmpfile=$(mktemp /tmp/abc-script.XXXXXX)
+	if not_in_tmux; then
 
-		while IFS= read -r path; do
-			if [ -d "$path" ]; then
-				printf "%s\n" "$path" >>"$tmpfile"
-			elif [ -f "$path" ]; then
-				printf "%s\n" "$(dirname "$path")" >>"$tmpfile"
-			fi
-		done <"$LIST"
+		if type find >/dev/null 2>&1; then
+			tmpfile=$(mktemp /tmp/abc-script.XXXXXX)
 
-		sel=$(xargs -d '\n' -I{} find {} -type f -printf "%H//%P\n" <"$tmpfile" | sed '/.*\/\/\(\..*\|.*\/\..*\)/d; s:/\+:/:g' | fzf --delimiter / --tiebreak=begin --info=hidden)
-		# Alternative for 'fd'
-		# sel=$(xargs -d '\n' < "$tmpfile" fd . | fzf --delimiter / --tiebreak=begin --info=hidden)
+			while IFS= read -r path; do
+				if [ -d "$path" ]; then
+					printf "%s\n" "$path" >>"$tmpfile"
+				elif [ -f "$path" ]; then
+					printf "%s\n" "$(dirname "$path")" >>"$tmpfile"
+				fi
+			done <"$LIST"
 
-		rm "$tmpfile"
-	else
-		printf "find missing"
-		read -r _
-		exit 1
-	fi
-fi
+			# sel=$(xargs -d '\n' -I{} find {} -type f -printf "%H//%P\n" <"$tmpfile" | sed '/.*\/\/\(\..*\|.*\/\..*\)/d; s:/\+:/:g' | fzf --delimiter / --tiebreak=begin --info=hidden)
+			# Alternative for 'fd'
+			# dunstify "$tmpfile"
 
-if [ -n "$sel" ]; then
-	if [ "$sel" = "." ] || { ! [ -d "$sel" ] && ! [ -f "$sel" ]; }; then
-		exit 0
-	fi
+			pane_id_right=$(wezterm cli get-pane-direction right)
+			wezterm cli split-pane --bottom --move-pane-id "$pane_id_right" >/dev/null
+			wezterm cli activate-pane-direction Up
 
-	# Check if the selected path returned by fzf command is absolute
-	case $sel in
-	/*) nnn_cd "$sel" "$CTX" ;;
-	*)
-		# Remove "./" prefix if it exists
-		sel="${sel#./}"
+			# sel=$(xargs -d '\n' fd -H -I . <"$tmpfile" | fzf --delimiter / --with-nth=-2,-1 --tiebreak=begin --info=hidden --prompt "Cd to> ")
+			sel=$(xargs -d '\n' fd -H -I . <"$tmpfile" | fzf --no-height --prompt "FzCD: ")
 
-		if [ "$PWD" = "/" ]; then
-			nnn_cd "/$sel" "$CTX"
+			wezterm cli split-pane --right --move-pane-id "$pane_id_right" --percent 85 >/dev/null
+			wezterm cli activate-pane-direction Left
+
+			rm "$tmpfile"
+
 		else
-			nnn_cd "$PWD/$sel" "$CTX"
+			printf "find missing"
+			read -r _
+			exit 1
 		fi
-		;;
-	esac
+	fi
+
+	if [ -n "$sel" ]; then
+		if [ "$sel" = "." ] || { ! [ -d "$sel" ] && ! [ -f "$sel" ]; }; then
+			exit 0
+		fi
+
+		# Check if the selected path returned by fzf command is absolute
+		case $sel in
+		/*) nnn_cd "$sel" "$CTX" ;;
+		*)
+			# Remove "./" prefix if it exists
+			sel="${sel#./}"
+
+			if [ "$PWD" = "/" ]; then
+				nnn_cd "/$sel" "$CTX"
+			else
+				nnn_cd "$PWD/$sel" "$CTX"
+			fi
+			;;
+		esac
+	fi
 fi
