fix(colors): remove unused code lines

diff --git a/rofi/.config/rofi/menu/_themes b/rofi/.config/rofi/menu/_themes
--- a/rofi/.config/rofi/menu/_themes
+++ b/rofi/.config/rofi/menu/_themes
@@ -9,6 +9,133 @@ ERROR_MSG="[!] Sorry..we abort it"
 NEW_FONTS="JetBrainsMono NF"
 NEW_FONTS_SIZE=16
 
+GET_FG=$(xrdb -query | grep -i foreground | cut -d':' -f2 | xargs)
+GET_BG=$(xrdb -query | grep -i background | cut -d':' -f2 | xargs)
+
+GET_BLACK=$(xrdb -query | grep -i .color0 | cut -d':' -f2 | head -1 | xargs)
+GET_BLACK_ALT=$(xrdb -query | grep -i .color8 | cut -d':' -f2 | head -1 | xargs)
+
+GET_RED=$(xrdb -query | grep -i .color1 | cut -d':' -f2 | head -1 | xargs)
+GET_RED_ALT=$(xrdb -query | grep -i .color9 | cut -d':' -f2 | head -1 | xargs)
+
+GET_GREEN=$(xrdb -query | grep -i .color2 | cut -d':' -f2 | head -1 | xargs)
+GET_GREEN_ALT=$(xrdb -query | grep -i .color10 | cut -d':' -f2 | head -1 | xargs)
+
+GET_YELLOW=$(xrdb -query | grep -i .color3 | cut -d':' -f2 | head -1 | xargs)
+GET_YELLOW_ALT=$(xrdb -query | grep -i .color11 | cut -d':' -f2 | head -1 | xargs)
+
+GET_BLUE=$(xrdb -query | grep -i .color4 | cut -d':' -f2 | head -1 | xargs)
+GET_BLUE_ALT=$(xrdb -query | grep -i .color12 | cut -d':' -f2 | head -1 | xargs)
+
+GET_MAGENTA=$(xrdb -query | grep -i .color5 | cut -d':' -f2 | head -1 | xargs)
+# GET_MAGENTA_ALT=$(xrdb -query | grep -i .color13 | cut -d':' -f2 | head -1 | xargs)
+
+GET_CYAN=$(xrdb -query | grep -i .color6 | cut -d':' -f2 | head -1 | xargs)
+# GET_CYAN_ALT=$(xrdb -query | grep -i .color14 | cut -d':' -f2 | head -1 | xargs)
+
+# GET_WHITE=$(xrdb -query | grep -i .color7 | cut -d':' -f2 | head -1 | xargs)
+# GET_WHITE_ALT=$(xrdb -query | grep -i .color15 | cut -d':' -f2 | head -1 | xargs)
+
+GET_COL_16="#6c8cac"
+GET_COL_17="#333333"
+GET_COL_18="#5b5b5b"
+GET_COL_19="#131313"
+GET_COL_20="#262626"
+GET_COL_21="#262626"
+GET_COL_22="#181818"
+GET_COL_23="#5f5f5f"
+GET_COL_24="#ffb49d"
+GET_COL_25="#2f2f2f"
+GET_COL_26="#5f5f5f"
+GET_COL_27="#ffb49d"
+GET_COL_28="#ffb49d"
+
+MASTER_THEME_FILE=/tmp/master-colors-themes
+
+if [[ -f "$MASTER_THEME_FILE" ]]; then
+  GET_COL_16=$(grep -i color16 <"$MASTER_THEME_FILE" | cut -d':' -f2 | head -1 | xargs)
+  GET_COL_17=$(grep -i color17 <"$MASTER_THEME_FILE" | cut -d':' -f2 | head -1 | xargs)
+  GET_COL_18=$(grep -i color18 <"$MASTER_THEME_FILE" | cut -d':' -f2 | head -1 | xargs)
+  GET_COL_19=$(grep -i color19 <"$MASTER_THEME_FILE" | cut -d':' -f2 | head -1 | xargs)
+
+  GET_COL_20=$(grep -i color20 <"$MASTER_THEME_FILE" | cut -d':' -f2 | head -1 | xargs)
+  GET_COL_21=$(grep -i color21 <"$MASTER_THEME_FILE" | cut -d':' -f2 | head -1 | xargs)
+  GET_COL_22=$(grep -i color22 <"$MASTER_THEME_FILE" | cut -d':' -f2 | head -1 | xargs)
+  GET_COL_23=$(grep -i color23 <"$MASTER_THEME_FILE" | cut -d':' -f2 | head -1 | xargs)
+  GET_COL_24=$(grep -i color24 <"$MASTER_THEME_FILE" | cut -d':' -f2 | head -1 | xargs)
+  GET_COL_25=$(grep -i color25 <"$MASTER_THEME_FILE" | cut -d':' -f2 | head -1 | xargs)
+  GET_COL_26=$(grep -i color26 <"$MASTER_THEME_FILE" | cut -d':' -f2 | head -1 | xargs)
+  GET_COL_27=$(grep -i color27 <"$MASTER_THEME_FILE" | cut -d':' -f2 | head -1 | xargs)
+  GET_COL_28=$(grep -i color28 <"$MASTER_THEME_FILE" | cut -d':' -f2 | head -1 | xargs)
+fi
+
+lighten_color() {
+  hex_color="$1"
+  factor="$2"
+
+  # Validasi panjang HEX
+  if [[ ${#hex_color} -ne 7 ]]; then
+    echo "Error: HEX color must be in the format '#RRGGBB'."
+    exit 1
+  fi
+
+  # Ekstraksi komponen warna
+  r=$(printf "%d" 0x"${hex_color:1:2}")
+  g=$(printf "%d" 0x"${hex_color:3:2}")
+  b=$(printf "%d" 0x"${hex_color:5:2}")
+
+  # Mencerahkan setiap komponen warna
+  r=$(($r + $factor))
+  g=$(($g + $factor))
+  b=$(($b + $factor))
+
+  # Batasi nilai maksimum ke 255
+  r=$(($r > 255 ? 255 : $r))
+  g=$(($g > 255 ? 255 : $g))
+  b=$(($b > 255 ? 255 : $b))
+
+  # Format kembali ke format HEX
+  printf "#%02x%02x%02x\n" "$r" "$g" "$b"
+}
+darken_color() {
+  hex_color="$1"
+  factor="$2"
+
+  # Validasi panjang HEX
+  if [[ ${#hex_color} -ne 7 ]]; then
+    echo "Error: HEX color must be in the format '#RRGGBB'."
+    exit 1
+  fi
+
+  # Ekstraksi komponen warna
+  r=$(printf "%d" 0x"${hex_color:1:2}")
+  g=$(printf "%d" 0x"${hex_color:3:2}")
+  b=$(printf "%d" 0x"${hex_color:5:2}")
+
+  # Menggelapkan setiap komponen warna
+  r=$(($r - $factor))
+  g=$(($g - $factor))
+  b=$(($b - $factor))
+
+  # Batasi nilai minimum ke 0
+  r=$(($r < 0 ? 0 : $r))
+  g=$(($g < 0 ? 0 : $g))
+  b=$(($b < 0 ? 0 : $b))
+
+  # Format kembali ke format HEX
+  printf "#%02x%02x%02x\n" "$r" "$g" "$b"
+}
+
+# check_size_screen() {
+#   size=$(xrandr | grep "*" | xargs | cut -d" " -f1)
+#
+#   if [[ $size == '1024x768' ]]; then
+#     FONTSIZE="12"
+#   else
+#     FONTSIZE="16"
+#   fi
+# }
+
 set_rofi() {
   _ROFI_PATH="$DOTFILES_PATH/rofi/.config/rofi"
 
@@ -67,19 +194,20 @@ set_tmux() {
 
   if [ -f "$_PATH_TMUX_THEMES" ]; then
     sleep 1
-    sed -i -e "s/^STATUSLINE_BG_ACTIVE=.*$/STATUSLINE_BG_ACTIVE=\"$GET_COL_16\"/g" "$_PATH_TMUX_THEMES"
+    sed -i -e "s/^STATUSLINE_FG_ACTIVE=.*$/STATUSLINE_FG_ACTIVE=\"$GET_COL_16\"/g" "$_PATH_TMUX_THEMES"
+    sed -i -e "s/^STATUSLINE_BG_ACTIVE=.*$/STATUSLINE_BG_ACTIVE=\"$GET_COL_17\"/g" "$_PATH_TMUX_THEMES"
+    sed -i -e "s/^STATUSLINE_FG=.*$/STATUSLINE_FG=\"$GET_COL_18\"/g" "$_PATH_TMUX_THEMES"
     sed -i -e "s/^STATUSLINE_BG=.*$/STATUSLINE_BG=\"$GET_BG\"/g" "$_PATH_TMUX_THEMES"
-    sed -i -e "s/^STATUSLINE_FG=.*$/STATUSLINE_FG=\"$GET_COL_17\"/g" "$_PATH_TMUX_THEMES"
 
     sed -i -e "s/^BORDER_BG=.*$/BORDER_BG=\"$GET_BG\"/g" "$_PATH_TMUX_THEMES"
     sed -i -e "s/^BORDER_FG=.*$/BORDER_FG=\"$GET_COL_17\"/g" "$_PATH_TMUX_THEMES"
-    sed -i -e "s/^BORDER_FG_NC=.*$/BORDER_FG_NC=\"$GET_COL_27\"/g" "$_PATH_TMUX_THEMES"
+    sed -i -e "s/^BORDER_FG_NC=.*$/BORDER_FG_NC=\"$GET_COL_19\"/g" "$_PATH_TMUX_THEMES"
 
-    sed -i -e "s/^SEPARATOR_FG=.*$/SEPARATOR_FG=\"$GET_COL_17\"/g" "$_PATH_TMUX_THEMES"
+    sed -i -e "s/^SEPARATOR_FG=.*$/SEPARATOR_FG=\"$GET_COL_25\"/g" "$_PATH_TMUX_THEMES"
     sed -i -e "s/^SEPARATOR_ACTIVE_BG=.*$/SEPARATOR_ACTIVE_BG=\"$GET_COL_27\"/g" "$_PATH_TMUX_THEMES"
 
-    sed -i -e "s/^WINDOW_BG_ACTIVE=.*$/WINDOW_BG_ACTIVE=\"$GET_COL_28\"/g" "$_PATH_TMUX_THEMES"
-    sed -i -e "s/^WINDOW_BG=.*$/WINDOW_BG=\"$GET_COL_28\"/g" "$_PATH_TMUX_THEMES"
+    sed -i -e "s/^WINDOW_BG_ACTIVE=.*$/WINDOW_BG_ACTIVE=\"$GET_COL_20\"/g" "$_PATH_TMUX_THEMES"
+    sed -i -e "s/^WINDOW_BG=.*$/WINDOW_BG=\"$GET_COL_21\"/g" "$_PATH_TMUX_THEMES"
 
     sed -i -e "s/^RED=.*$/RED=\"$GET_RED\"/g" "$_PATH_TMUX_THEMES"
     sed -i -e "s/^BLUE=.*$/BLUE=\"$GET_BLUE\"/g" "$_PATH_TMUX_THEMES"
@@ -147,7 +275,6 @@ set_terminal() {
     dunstify "theme alacritty [-]"
   fi
 }
-
 set_btop() {
   _BTOP_PATH="$DOTFILES_PATH/btop/.config/btop"
 
@@ -186,7 +313,6 @@ set_btop() {
   sed -i -e "s/%%background_darken_2%%/$BACKGROUND_DARKEN_1/g" "$_BTOP_PATH/themes/guard_theme.theme"
 
 }
-
 set_yazi_theme() {
   YAZI_FILE_THEME="$HOME/.config/yazi/theme.toml"
 
@@ -201,7 +327,6 @@ set_yazi_theme() {
 
   sed -i -e "s/^use.*/use = \"$NAME_THEME\"/g" "$YAZI_FILE_THEME"
 }
-
 set_fzf() {
   FZF_PATH_CONFIG="$HOME/moxconf/development/dotfiles/miscxrdb/.config/miscxrdb/fzf"
 
@@ -211,20 +336,19 @@ set_fzf() {
 
   cat "$FZF_PATH_CONFIG/_fzf.config" >"$FZF_PATH_CONFIG/fzf.config"
 
-  sed -i -e "s/%%color_bg%%/$GET_COL_19/g" "$FZF_PATH_CONFIG/fzf.config"
-  sed -i -e "s/%%color_fg%%/$GET_COL_20/g" "$FZF_PATH_CONFIG/fzf.config"
-  sed -i -e "s/%%color_hl%%/$GET_COL_21/g" "$FZF_PATH_CONFIG/fzf.config"
+  sed -i -e "s/%%color_bg%%/$GET_COL_22/g" "$FZF_PATH_CONFIG/fzf.config"
+  sed -i -e "s/%%color_fg%%/$GET_COL_23/g" "$FZF_PATH_CONFIG/fzf.config"
+  sed -i -e "s/%%color_hl%%/$GET_COL_24/g" "$FZF_PATH_CONFIG/fzf.config"
 
-  sed -i -e "s/%%color_selection_bg%%/$GET_COL_22/g" "$FZF_PATH_CONFIG/fzf.config"
-  sed -i -e "s/%%color_selection_fg%%/$GET_COL_23/g" "$FZF_PATH_CONFIG/fzf.config"
-  sed -i -e "s/%%color_selection_hl%%/$GET_COL_24/g" "$FZF_PATH_CONFIG/fzf.config"
+  sed -i -e "s/%%color_selection_bg%%/$GET_COL_25/g" "$FZF_PATH_CONFIG/fzf.config"
+  sed -i -e "s/%%color_selection_fg%%/$GET_COL_26/g" "$FZF_PATH_CONFIG/fzf.config"
+  sed -i -e "s/%%color_selection_hl%%/$GET_COL_26/g" "$FZF_PATH_CONFIG/fzf.config"
 
-  sed -i -e "s/%%color_border%%/$GET_COL_25/g" "$FZF_PATH_CONFIG/fzf.config"
-  sed -i -e "s/%%color_gutter%%/$GET_COL_19/g" "$FZF_PATH_CONFIG/fzf.config"
+  sed -i -e "s/%%color_border%%/$GET_COL_28/g" "$FZF_PATH_CONFIG/fzf.config"
+  sed -i -e "s/%%color_gutter%%/$GET_COL_22/g" "$FZF_PATH_CONFIG/fzf.config"
   sed -i -e "s/%%color_pointer%%/$GET_RED/g" "$FZF_PATH_CONFIG/fzf.config"
 
 }
-
 set_lazygit() {
   LAZYGIT_PATH="$HOME/.config/lazygit"
   THEME_LAZYGIT="$LAZYGIT_PATH/themes/_themes_cfg"
@@ -232,20 +356,21 @@ set_lazygit() {
   if [ -f "$THEME_LAZYGIT" ]; then
     cp "$LAZYGIT_PATH/themes/_themes" "$THEME_LAZYGIT"
 
-    border_color=$(lighten_color "$GET_COL_27" 10)    # Misalnya, mengurangi 50 untuk menggelapkan
-    default_fg_color=$(lighten_color "$GET_COL_17" 25) # Misalnya, mengurangi 50 untuk menggelapkan
+    # border_color=$(lighten_color "$GET_COL_17" 10)     # Misalnya, mengurangi 50 untuk menggelapkan
+    default_fg_color=$(lighten_color "$GET_COL_17" 50) # Misalnya, mengurangi 50 untuk menggelapkan
+
+    selected_line_bg_color=$(darken_color "$GET_COL_16" 80) # Misalnya, mengurangi 50 untuk menggelapkan
 
     sed -i -e "s/%%active_border_color%%/$GET_COL_16/g" "$THEME_LAZYGIT"
-    sed -i -e "s/%%inactive_border_color%%/$border_color/g" "$THEME_LAZYGIT"
+    sed -i -e "s/%%inactive_border_color%%/$GET_COL_17/g" "$THEME_LAZYGIT"
     sed -i -e "s/%%options_text_color%%/$GET_COL_20/g" "$THEME_LAZYGIT"
-    sed -i -e "s/%%selected_line_bg_color%%/$GET_COL_22/g" "$THEME_LAZYGIT"
+    sed -i -e "s/%%selected_line_bg_color%%/$selected_line_bg_color/g" "$THEME_LAZYGIT"
     sed -i -e "s/%%default_fg_color%%/$default_fg_color/g" "$THEME_LAZYGIT"
 
     cat "$LAZYGIT_PATH/_config.yml" "$THEME_LAZYGIT" >"$LAZYGIT_PATH/config.yml"
   fi
 
 }
-
 set_eww() {
   EWW_PATH="$HOME/.config/eww"
 
@@ -274,16 +399,6 @@ set_eww() {
   sed -i -e "s/^\$cyan: .*/\$cyan: $GET_CYAN;/g" "$EWW_PATH/eww.scss"
 
 }
-
-wm_bspwm() {
-  ~/.config/bspwm/bspwmrc &>/dev/null
-  # ~/.config/bspwm/bspwmrc
-  # ~/.config/polybar/runpolybar.sh &>/dev/null
-}
-wm_awesome() {
-  echo "awesome.restart()" | awesome-client
-}
-
 set_firefox() {
   IGET_CUS="$(xrdb -query | grep 'color8:' | awk '{print $NF}' | head -1)"
 
@@ -305,6 +420,15 @@ set_firefox() {
     dunstify "$ERROR_MSG" "Path $FIREFOX_DEFAULT_PATH do not exists!"
   fi
 
+}
+
+wm_bspwm() {
+  ~/.config/bspwm/bspwmrc &>/dev/null
+  # ~/.config/bspwm/bspwmrc
+  # ~/.config/polybar/runpolybar.sh &>/dev/null
+}
+wm_awesome() {
+  echo "awesome.restart()" | awesome-client
 }
 
 dir="$HOME/.config/rofi/menu"
@@ -347,7 +471,6 @@ rofi_command="rofi -modi drun -theme $dir/$theme -show drun"
 
   xrdb -merge ~/.Xresources
   #shellcheck source=/dev/null
-  . ~/.config/miscxrdb/exbin/get_xrdb_vars
 
   sleep 1
   set_rofi
